
- include: gather_facts.yml

- ec2:
    state: 'absent'
    aws_access_key: "{{ ec2_access_key  }}"
    aws_secret_key: "{{ ec2_secret_key  }}"
    region: eu-west-1
    wait: yes
    instance_ids: '{{ item.id }}'
  with_items: '{{ec2_facts.instances}}'