- debug: var=nginx_welcome_page_enabled

- name: Replace default nginx conf
  template: src=default.j2 dest="/etc/nginx/conf.d/default.conf"
  register: nginx_conf

- name: Restart nginx when nginx conf is updated
  docker_container:
    name: nginx
    image: nginx
    state: started
    restart: yes
  when: nginx_conf | changed