- debug: var=nginx_welcome_page_enabled

- name: Ensure nginx html folder exists
  file:
    path: /usr/share/nginx/html
    state: directory

- name: Replace welcome page
  template: src=files/index.html dest="/usr/share/nginx/html"
  register: index_html

- name: Ensure nginx conf folder exists
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: Replace default nginx conf
  template: src=default.j2 dest="/etc/nginx/conf.d/default.conf"
  register: nginx_conf

- name: Restart nginx when nginx conf is updated
  docker_container:
    name: nginx
    image: nginx
    state: started
    restart: yes
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - /usr/share/nginx/html:/usr/share/nginx/html:ro
  when: nginx_conf | changed or index_html | changed